### ISSUE TITLE
Úkol_01: Pandas & visualization: volby USA

### ISSUE THREAD

**Issue by zitkovalenka** [zitkovalenka/Python2-042023#1]
https://github.com/zitkovalenka/Python2-042023/blob/main/UKOL_01-VOLBY_USA.ipynb

Odevzdávám úkol č. 1. Prosím o radu s posledním bodem druhé části úkolu (bod 4.)

"Vytvoř pivot tabulku, která zobrazí pro jednotlivé volební roky, kolik států přešlo od Republikánské strany k Demokratické straně, kolik států přešlo od Demokratické strany k Republikánské straně a kolik států volilo kandidáta stejné strany."

Pomocí vytvoření vlastní funkce a metody apply se snažím funkci volat. Bohužel mám někde chybu, ať zkouším, jak zkouším. Jsou k dispozici 2 verze (2 poslední kódy) a ani jeden není zcela funkční. Jedná se zatím o část, kdy chci přidat sloupec "swing" a do něj plnit hodnoty "no swing" , "to Rep", "to Dem".

Mockrát děkuji za radu,
Lenka

**Comment by M-Kovar** [comment]
Ahoj Lenko,

prošel jsem úkol, máš to pěkné a většina funguje podle očekávání, takže píšu splněno:-). Přidávám pár poznámek, podle kterých můžeš úkol dobrovolně aktualizovat a znova commitnout...

- Bod 3, přidání `previous_winner_party`: Tady je vhodné shiftovat na datech seskupených podle států, protože jinak se třeba poslední výsledek (2020) Alabamy posune k prvnímu (1976) z Aljašky, což nechceme. Pomocí groupby tedy ohraničíme jednotlivé státy: `df_volby_vitez["Previous_winner_party"] = df_volby_vitez.groupby("state")["party_simplified"].shift(1)`

- Bod 4, porovnání stran: Není mi jasné použití dvakrát za sebou numpy.where (hádám, že ten první jen není zakomentovaný), ale každopádně oba dva dávají požadovaný výsledek.

- Bod 6, graf: Pro zajímavost, popisky států můžeš natočit pomocí `plt.xticks(rotation=45)`. V tomhle případě to teda kvůli některým dlouhým názvům čitelnosti kdovíjak nepomůže, ale zkrátka je to taky možnost:).

- Další část, bod 1, rozdíl hlasů: Stejně jako u předchozího shiftu, i tady je potřeba grupovat, abychom neposouvali mezi našimi přihládkami: `df_volby_2["Second_candidatevotes"] = df_volby_2.groupby(["year", "state"])["candidatevotes"].shift(-1)`.

- Další část, bod 4, funkce `to_swing`: V první variantě funkce je potřeba používat jen `row` namísto celého `df_volby_vitez_filtered`. Blíž k fungování má tedy Tvoje druhá varianta, kde už jen stačí `&` nahradit klasickým pythonovským `and`. Není mi jasné, k čemu slouží `row = row.iloc[15:]`, ale pokud k výběru sloupců, tak to není potřeba, jelikož je pak stejně vybíráme podle jména. Ještě pro jistotu varuju, že else se váže jen k poslednímu ifu - pokud bys chtěla všechno mít "pod jednou podmínkou", použij if/elif/else. A pak dokonce když prvním ifem ověříš, že strany nejsou stejné, tak můžeš vracet výsledek už jen na základě `row["party_simplified"]`. Pak může funkce vypadat takhle:
```
def to_swing(row):
    if row["party_simplified"] == row["Previous_winner_party"]:
       return "no swing"
    elif row["party_simplified"] == "DEMOCRAT":
       return "to Rep"
    elif row["party_simplified"] == "REPUBLICAN":
       return "to Dem"
    else:
       return "chyba"
```

- Další část, bod 4, pivot tabulka: Pro sečtení, kolik států jak swingovalo, můžeš použít grupování podle sloupce Swing a v tomhle případě přes pivot_table(), abychom seskupili rovnou i roky. Výsledek pak může vypadat takhle: `df_volby_vitez_filtered.pivot_table(index="year", columns="Swing", values="state", aggfunc="count", margins=True)`

Celkově pěkná práce :-). Kdyby něco nebylo jasné, klidně dořešíme.

**Comment by zitkovalenka** [comment]
Ahoj Martine,

upravila jsem některé kódy. Zejm. groupby. Nějak jsem na to zapomněla a je pravda, že teď to dělá přesně to, co má. Předtím tam chybělo "NaN". Měla jsem za to, že to tam mám, ale neměla.

Druhá část, bod č. 4:
Myslím, že máš obráceně přiřazení "to Rep" a "to Dem", tak jsem to otočila. Nicméně jsem chtěla napsat kód s query (row.query) a píše mi to, že to zde nelze. Opravdu to nelze nebo mám něco špatně? Raději bych to měla rozepsané v tomto smyslu. Pro mě je to čitelnější a jsem si hlavně jistá, že to pak dělá to, co chci. Sice rozumím, proč to stačí napsat takto `party_simplified == "DEMOCRAT"`, ale já si jsem více jistá níže uvedeným:

> def to_swing(row):
   if row["party_simplified"] == row["Previous_winner_party"]:
     return "no swing"
   elif row.query("party_simplified = REPUBLICAN" and "Previous_winner_party = DEMOCRAT"):
      return "to Rep"
   elif row.query("party_simplified = DEMOCRAT" and "Previous_winner_party = REPUBLICAN"):
      return "to Dem"
   else:
      return "chyba"

> 


Dál jsem se tě chtěla zeptat na reálný rozdíl mezi tím, že použiji zde "elif" nebo "if". V jednom úkolu právě bylo použito jen if několikrát pod sebou. Třeba na tomto příkladu.

A ano, iloc neměl smysl zde, já jen zkoušela všechno možné, abych kód rozchodila :-) .

Děkuji,
Lenka

**Comment by M-Kovar** [comment]
Ahoj Lenko,

- Pravda, "to Rep" a "to Dem" jsem omylem přehodil, dobrý postřeh:). A souhlasím, že kód, který jsi poslala, je takový explicitnější a jasnější na pochopení.

- V té funkci se `row` skrz `apply()` dostává jako typ Series, na kterém vlastně už nemá smysl `query()` volat, jelikož to slouží k výběru řádků z DataFramu - row je jen jeden řádek, takže už není co vybírat. Ale kdybys query chtěla použít na celou tabulku, bude podmínka vypadat třeba takto: `df_volby_vitez_filtered.query("party_simplified == 'REPUBLICAN' and Previous_winner_party == 'DEMOCRAT'")` ... tzn. celý dotaz uzavřený v uvozovkách (včetně and), dvojité rovnítko pro porovnávání a ještě jednoduché uvozovky kolem porovnávaných stringů REPUBLICAN a DEMOCRAT.

- If vs elif nemusí dávat jiný výsledek, ale rozdíl je v tom, že postupné ify jsou na sobě nezávislé - vyhodnocují se tedy všechny a při nevylučujících se podmínkách jich může nastat i víc. Zatímco if+elify jsou spolu svázané, takže se provede jen jedna možnost. Každé se hodí na něco jiného. V našem případě jsou if+elify teoreticky efektivnější z hlediska náročnosti zpracování, jelikož pokud platí třeba hned první podmínka, tak už se další nevyhodnocují a program pokračuje dál - zatímco samostatné ify by se zbytečně ještě vyhodnocovaly.

**Comment by zitkovalenka** [comment]
Já myslela spíš, jak to udělat, aby v definici vlastní funkce (tedy pro nás to_swing(row), se dala použít složená podmínka. Např. něco jako toto:

`elif (row["party_simplified"] == "DEMOCRAT" & row["Previous_winner_party"] == "DEMOCRAT"):`

Supr vysvětlení rozdílu if a elif. Děkuji.

**Comment by M-Kovar** [comment]
Aha, už asi začínám chápat:). V podmínkách můžeš používat `and` nebo `or` a obalovat závorkama podle potřeby. Takže podmínka, kterou jsi poslala, bude až na `&` úplně stejná:

`elif row["party_simplified"] == "DEMOCRAT" and row["Previous_winner_party"] == "DEMOCRAT"`
