### ISSUE TITLE
Úkol_03: Regression model

### ISSUE THREAD

**Issue by zitkovalenka** [zitkovalenka/Python2-042023#2]
https://github.com/zitkovalenka/Python2-042023/blob/main/UKOL_03-reseni-Korelace_Regrese.ipynb

Martine,
odevzdávám úkol č.3 na regresní model. V průběhu kódu  mám vložené nějaké otázky, které shrnuji také sem:

1. Použila jsem graf regplot z modulu seaborn. Pokud jsem nechala lineární regresi, křivka se mi nezdála, jelikož  mi body evokují sami o sobě logaritmickou křivku. Doplnila jsem tedy do grafu logx = True, což právě vytvořilo pomocí metody nejmenších čtverců logaritmickou křivku, která lépe vystihuje rozesetí pozorování (bodů). Je to tak správně?

2. Některé body (zejména ty zcela vpravo) se mi zdáli dost oddělené, použila jsem tedy Z-scóre pro odstranění odlehlých pozorování (outliers), ale nic se nestalo (počty řádků jsou stejné v dataframe "data2015" i "data2015_wo_outliers")

3. Nejsem si jistá, na kterou hodnotu P>|t| se mám dívat, abych věděla, jestli je koeficient statisticky významný? Třeba hned v prvním bodě, kde existuje formula "Life_expectancy ~ GDP_per_capita". Pokud je tato hodnota 0.000 (tedy na řádku s GDP_per_capita je 0.000), pak se jedná o proměnnou, která je statisticky významná? (má hodnotu <0.05).

4. Metodu nejmenších čtverců můžeme použít pro jakékoliv rozdělení (normální, logaritmické apod.?).

5. V bodě, kde odstraňuji proměnnou "Measles", jelikož má druhou nejvyšší hodnotu P>|t| (jen zkouším dál, vím, že to není v zadání). Změní se zejména hodnoty Prob(Omnibus): 0.215 a Prob(JB): 0.208 (téměř se zdvojnásobí oproti předchozímu modelu). Vím, že stále nezamítáme hypotézu normálního rozdělení reziduí, ale hodnota je téměř dvojnásobná. Co to znamená?

6. Zkusila jsem si navíc test normality dat pomocí Shapiro a zde vyšlo P-value = 1.0978403224726208e-05   --> tzn. menší než 0.05, což znamená, že data nemají normální rozdělení (a nemůžeme na ně použít parametrické testy).

Jak to ale, že podle Prob(Omnibus) vždy nezamítáme hypotézu normálního rozdělení, ale přitom data podle testu Shapiro normální rozdělení nemají? Vyplývá to i z grafu, který je spíše logaritmický. Tomuto rozporu moc nerozumím, dokázal bys ho prosím vysvětlit?

Mockrát děkuji,
Lenka

**Comment by zitkovalenka** [comment]
Ahoj Martine,

upravila jsem kód a mám jen 2 otázky :-) : 
1. V případě, že Prob(Omnibus) = 0.050 a Prob(JB) = 0.0605 --> lze NEzamítnout hypotézu normálního rozdělení reziduí (>0.05), ačkoliv má být koeficient větší než 0,.05, ne rovno 0.05? Prob(JB) je 0.060 (tedy nad 0.05). Můžeme tedy využít další statistické koeficienty?
2. Zkusila jsem si navíc test normality dat pomocí Shapiro a zde vyšlo P-value = 1.0978403224726208e-05 --> tzn. menší než 0.05, což znamená, že data nemají normální rozdělení (a nemůžeme na ně použít parametrické testy). Jak to, že nám dle Prob(Omnibus) vyšlo, že je to těsně k NEzamítnutí hypotézy o normálním rozdělení?

Děkuji za vysvětlení, kontrolu a případné připomínky k úkolu.

Lenka

**Comment by M-Kovar** [comment]
Ahoj Lenko,

píšu splněno, ponořila ses do toho poctivě a důkladně:). Máš to vše pěkně popsané a souhlasím s tím, jak jsi analýzu provedla. Pokusím se odpovědět na otázky, ale upozorňuju, že nejsem expert, takže kdybys něčím nebyla spokojená, klidně to prober ještě s Jirkou:

- Popisek v grafu: Parametr `label` lze použít, jen je potřeba následně zobrazit popisek v grafu jakožto legendu pomocí `g.legend()`. Konrétně pro regplot nejde přes label pojmenovat jak data, tak regresní přímku (label bude jen k datům), takže můžeš legendu vytvořit dodatečně ručně jako `g.legend(["data","line"])`. Případně vyplotovat čáru ještě zvlášť a dát ji vlastní label: `seaborn.regplot(data2015, x="GDP_per_capita", y="Life_expectancy", scatter=False, label="Regression line")`.

- Omnibus vs JB: Když je výsledek na hranici, resp. když každý test vyjde jinak, asi bych zkusil zjistit příčiny nebo upravit data tak, aby to vyšlo jednoznačněji. Lze se na data podívat graficky a odborným okem posoudit, jestli jsou blíž normalitě, případně odhalit, co způsobuje nenormalitu a to vyřešit (třeba odstranění outlierů nebo transformace dalších proměnných). Případně prozkoumat vlastnosti testů a vybrat reprezentativnější pro náš případ. Z vyšší perspektivy je ale pořád potřeba umět každý krok obhájit a interpretovat a myslet i na praktickou významnost výsledků, k čemuž je ideální být vědcem v oboru a dopodrobna rozumět těm datům. Když to vezmeme z pohledu přípravy nějakého vědeckého článku: čísla můžou vyjít krásně, ale když budou metodologie pokusu nebo posbíraná data pochybná, kolegové vědci budou k výsledkům skeptičtí, a naopak když se podaří třeba solidně vysvětlit hraniční čísla a vše okolo obhájit, může být výsledná důvěra velká.

- Výsledky Shapiro vs Omnibus: Nejsem si jistý, jaké proměnné jsi uvažovala v otázce, tak odpovím obecně... Zaprvé, každý test funguje jinak, takže i výsledky se můžou lišit, a to hlavně u menšího počtu dat, čemuž se s 179 vzorky blíží i naše data. Zadruhé (a tohle jsi asi uvažovala, ale pro jistotu), Shapiro bere jen jednu proměnnou, zatímco Omnibus všechny proměnné v modelu.

- Nevyloučení proměnné, když se jejím vyloučením poruší normalita: Souhlasím s nevylučováním, jelikož předpoklad normality pro model potřebujeme. Případně opět můžeme zkusit zařídit normalitu úpravou dat. A opět se hodí umět ne/odebrání a význam proměnné v modelu interpretovat a obhájit.
