### ISSUE TITLE
Úkol_02: Hypothesis testing

### ISSUE THREAD

**Issue by zitkovalenka** [zitkovalenka/Python2-042023#3]
https://github.com/zitkovalenka/Python2-042023/blob/main/UKOL_02-reseni-TESTOVANI_HYPOTEZ.ipynb

Martine,

odevzdávám úkol na testování hypotéz.

Děkuji za kontrolu a případné připomínky,
Lenka

**Comment by M-Kovar** [comment]
Ahoj Lenko,

moc pěkné, píšu splněno. Pár komentářů (neokomentovaný většinový zbytek kódu je bezchybný):

- "Ověř, zda existuje korelace mezi procentem lidí, které věří EU v každé ze zemí, a procentem lidí, kteří EU nevěří": Tady je špatné vyjádření v zadání, kterou Jirka asi zapomněl opravit. Podle kontextu zpracovávaných dat má jít o důvěru ve vládu versus EU. Hypotézy jsou tedy `Důvěra v národní vládu a důvěra v EU jsou lineárně (ne)závislé`, nicméně výpočet zůstává stejný a H0 zamítáme... Ještě upozorňuju na "lineárně", jelikož pearsonem zkoumáme korelaci jakožto lineární vztah.

- ...Pro zajímavost, existují i metody pro nelineární korelaci, např. "distance correlation". Podrobnosti neznám, jen jsem si přečetl, že existuje:).

- Důvěra států s eurem versus bez: Tady testujeme jen rozdíl průměru mezi dvěma sadami dat (proto dvouvýběrový T-test), ale ne specificky, jestli je jeden průměr menší nebo větší. Na to bychom použili jednostranný test (namísto oboustranného), což je téma na dobrovolné samostudium (i pro mě:). Tím pádem hypotézy bychom měli "zmírnit" na `Průměrná důvěra v EU se (ne)liší ve státech v eurozóně a ve státech mimo eurozónu`. Závěr by pak byl, že se neprokázalo, že by se důvěra lišila.

**Comment by zitkovalenka** [comment]
Ahoj Martine,

jen pro ujasnění, že chápu správně. 

**- 2. část: Důvěra ve stát a v EU:**
Otázka má být ve skutečnosti otázka postavena takto:

"Ověř, zda existuje korelace mezi důvěrou v národní vládu a důvěrou v EU."
Chápu to správně?

Výpočet je stejný, jako mám, jen následně hypotéza by měla být formulovaná:
H0: Důvěra v národní vládu a důvěra v EU NEjsou lineárně závislé.
H1: Důvěra v národní vládu a důvěra v EU jsou lineárně závislé."

Výsledek: (zamítáme H0): "`ZAMÍTÁME, že důvěra v národní vládu a důvěra v EU NEjsou lineráně závislé.`"

Toto zadání jsem si v hlavě zjednodušila už v původním řešení právě na tu důvěru v národní vládu vs v EU :-) .

**- 3. část: Důvěra států v EU a Euro:**
Píšeš, že využijeme dvouvýběrový T-test. Tady si nejsem jistá, co tím myslíš - `T-test` (nepárový T-test) nebo naopak `Paired T-test` (párový T-test).
Já předpokládám, že se jedná o ten nepárový, který používám v kódu.

Hypotézy po  zmírnění:
H0: Průměrná důvěra v EU se neliší ve státech v eurozóně a ve státech mimo eurozónu.
H1: Průměrná důvěra v EU se liší ve státech v eurozóně a ve státech mimo eurozónu.

Výsledek:  (nezamítáme H0) `NEzamítáme, že se průměrná důvěra v EU neliší ve státech v eurozóně a ve státech mimo eurozónu`. Tzn. neprokázalo se, že by se důvěra lišila.

Jde mi hlavně o to, jestli volím HO a H1 správně a správně pak interpretuji výsledek.

Mockrát děkuji,
Lenka

**Comment by M-Kovar** [comment]
Ano, všechno chápeš správně a hypotézy i výsledky máš taky dobře:-). A nepárový T-test je taky správně.

Ke kategoriím testů
- Párové vs nepárové: Párové se používají často v případech "před a po". Pár = data třeba od jednoho pacienta před léčbou a po léčbě. My bereme různé státy, takže používáme nepárový. Párový by mohl třeba sloužit pro otestování změny v důvěře k EU před vstupem do EU a po - tím pádem bychom pro každý stát použili data před a po.
- Jednovýběrové vs dvouvýběrové: Tady máme dvě sady dat (státy s eurem, státy bez eura) a porovnáváme je, proto dvouvýběrový. Neboli "výběr" = sada dat. Jednovýběrové se používají pro porovnání jedné sady dat s nějakým parametrem (obvykle průměrem) - můžeme tak určit, jestli je průměr sady dat statisticky významně odlišný od předpokládaného nebo známého průměru.

**Comment by zitkovalenka** [comment]
Děkuji. Tvá formulace hypotéz a hlavně výsledků hypotéz je daleko srozumitelnější a lidštější. Mé jsou docela krkolomné. To jsou ty zkušenosti ;-)
